{% set python_min = '3.10.0' %}
{% set name = "pit-rift" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pit_rift-{{ version }}.tar.gz
  sha256: b5fb0f4e1d798952887ae9cf351c4a2c677678363049f7ba1b7fb38c4a391179

build:
  entry_points:
    - rift = rift.management:start_from_command_line_interface
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pyyaml >=6.0.1,<7.0.0
    - pydantic >=2.8.2,<3.0.0
    - psutil >=6.0.0,<7.0.0
    - pytest >=8.3.2,<9.0.0
    - pytest-mock >=3.14.0,<4.0.0

test:
  imports:
    - rift
  commands:
    - pip check
    - rift --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pit-rift/
  summary: Parametrized Integration Testing framework Tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anto6715
